"use strict";

module.exports = Object.freeze({
  SCALE_BAUD: 9600,
  SCALE_SESSION_IDLE_MS: 120000,
  SCALE_OPEN_TIMEOUT_MS: 2000,
  SCALE_ENQ_TIMEOUT_MS: 800,
  SCALE_FRAME_TIMEOUT_MS: 1200,
  SCALE_READ_BUDGET_MS: 2500,
  /** Leitura em sessão já aberta (hot path frente de caixa). */
  SCALE_HOT_READ_BUDGET_MS: 900,
  SCALE_LOCK_WAIT_MS: 1500,
  SCALE_SOFT_RETRIES: 1,
  SCALE_SOFT_RETRY_MS: 150,
  /** Soft retry mais curto no hot path. */
  SCALE_HOT_SOFT_RETRY_MS: 80,
  SCALE_REOPEN_BACKOFF_MS: 300,
  SCALE_REOPEN_BACKOFF_MAX_MS: 2000,
  SCALE_MAX_REOPEN_ATTEMPTS: 2,
  SCALE_RX_BUFFER_MAX_BYTES: 256,
  SCALE_STATUS_CACHE_MS: 3000,
  SCALE_LIST_CACHE_MS: 15000,
  /** Soft errors (UNSTABLE/TIMEOUT) saem do health após TTL. */
  SCALE_SOFT_ERROR_TTL_MS: 45000,
});
