CREATE TABLE public.finance_categoria_custo (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    natureza_id uuid NOT NULL,
    categoria_pai_id uuid,
    codigo character varying(40) NOT NULL,
    nome character varying(120) NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.finance_centro_custo (
    id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    codigo character varying(20) NOT NULL,
    nome character varying(120) NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    setor_producao character varying(20)
);

CREATE TABLE public.finance_conta_pagar (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    fornecedor_id uuid,
    fornecedor_nome character varying(200),
    descricao character varying(300) NOT NULL,
    documento character varying(60),
    valor numeric(19,4) NOT NULL,
    vencimento date NOT NULL,
    data_pagamento date,
    valor_pago numeric(19,4),
    status character varying(20) DEFAULT 'ABERTA'::character varying NOT NULL,
    observacao text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    centro_custo_id uuid,
    nota_fiscal_entrada_id uuid,
    numero_duplicata character varying(60),
    categoria_custo_id uuid,
    loja_id uuid,
    recorrencia_id uuid,
    anexo_url character varying(500),
    aprovado_por uuid,
    aprovado_em timestamp without time zone,
    created_by uuid,
    competencia character varying(7),
    colaborador_id uuid,
    origem character varying(30),
    CONSTRAINT chk_finance_conta_pagar_status CHECK (((status)::text = ANY ((ARRAY['ABERTA'::character varying, 'PENDENTE_APROVACAO'::character varying, 'PAGA'::character varying, 'CANCELADA'::character varying])::text[])))
);

CREATE TABLE public.finance_natureza_custo (
    id uuid NOT NULL,
    codigo character varying(20) NOT NULL,
    nome character varying(80) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.pdv_caixa (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    operador character varying(80) NOT NULL,
    abertura_em timestamp without time zone DEFAULT now() NOT NULL,
    fechamento_em timestamp without time zone,
    valor_abertura numeric(19,4) DEFAULT 0 NOT NULL,
    valor_fechamento numeric(19,4),
    observacao character varying(255),
    status character varying(10) DEFAULT 'ABERTO'::character varying NOT NULL,
    numero_caixa character varying(20),
    dispositivo_id bigint,
    caixa_terminal_id uuid,
    CONSTRAINT chk_caixa_status CHECK (((status)::text = ANY ((ARRAY['ABERTO'::character varying, 'FECHADO'::character varying])::text[])))
);

CREATE TABLE public.pdv_cliente (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    tipo_pessoa character varying(2) DEFAULT 'PF'::character varying NOT NULL,
    cpf_cnpj character varying(18) NOT NULL,
    nome_razao_social character varying(120) NOT NULL,
    telefone character varying(20),
    email character varying(120),
    cep character varying(8),
    logradouro character varying(120),
    numero character varying(20),
    complemento character varying(60),
    bairro character varying(60),
    municipio character varying(60),
    uf character varying(2),
    codigo_ibge character varying(7),
    inscricao_estadual character varying(20),
    ind_ie_dest smallint,
    criado_em timestamp without time zone DEFAULT now() NOT NULL,
    atualizado_em timestamp without time zone DEFAULT now() NOT NULL,
    segmento character varying(20) DEFAULT 'NAO_CLASSIFICADO'::character varying NOT NULL,
    ticket_medio_cents bigint DEFAULT 0 NOT NULL,
    total_compras_count integer DEFAULT 0 NOT NULL,
    total_compras_cents bigint DEFAULT 0 NOT NULL,
    ultima_compra_at timestamp without time zone,
    primeiro_compra_at timestamp without time zone,
    score_recencia integer DEFAULT 0 NOT NULL,
    score_frequencia integer DEFAULT 0 NOT NULL,
    score_monetario integer DEFAULT 0 NOT NULL,
    whatsapp_marketing_consent boolean DEFAULT false NOT NULL,
    telefone_normalizado character varying(20),
    whatsapp_opt_out boolean DEFAULT false NOT NULL,
    ativo boolean DEFAULT true NOT NULL
);

CREATE TABLE public.pdv_crediario_cliente (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    limite_credito numeric(19,4) DEFAULT 500.00 NOT NULL,
    saldo_devedor numeric(19,4) DEFAULT 0 NOT NULL,
    status character varying(20) DEFAULT 'ATIVO'::character varying NOT NULL,
    observacao character varying(255),
    criado_em timestamp without time zone DEFAULT now() NOT NULL,
    atualizado_em timestamp without time zone DEFAULT now() NOT NULL,
    cliente_id uuid,
    dia_vencimento integer DEFAULT 10 NOT NULL,
    max_parcelas integer DEFAULT 3 NOT NULL,
    motivo_bloqueio text,
    aprovado_por character varying(120),
    aprovado_em timestamp without time zone,
    juros_atraso_percentual_mes numeric(5,2),
    multa_atraso_percentual numeric(5,2),
    dias_bloqueio_inadimplencia integer DEFAULT 30 NOT NULL,
    dias_carencia_juros integer,
    dias_carencia_multa integer,
    modo_aplicacao_encargos character varying(40),
    periodicidade character varying(20)
);

CREATE TABLE public.pdv_crediario_conta (
    id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    crediario_cliente_id uuid NOT NULL,
    venda_id uuid,
    numero_conta character varying(32) NOT NULL,
    valor_total numeric(19,4) NOT NULL,
    valor_pago numeric(19,4) DEFAULT 0 NOT NULL,
    valor_pendente numeric(19,4) NOT NULL,
    status character varying(24) DEFAULT 'ABERTA'::character varying NOT NULL,
    data_venda timestamp without time zone DEFAULT now() NOT NULL,
    observacoes text,
    criado_em timestamp without time zone DEFAULT now() NOT NULL,
    atualizado_em timestamp without time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.pdv_crediario_encargo (
    id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    parcela_id uuid NOT NULL,
    tipo character varying(16) NOT NULL,
    valor numeric(19,4) NOT NULL,
    data_calculo date NOT NULL,
    data_referencia_atraso date NOT NULL,
    criado_em timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_crediario_encargo_tipo CHECK (((tipo)::text = ANY ((ARRAY['JUROS'::character varying, 'MULTA'::character varying])::text[]))),
    CONSTRAINT chk_crediario_encargo_valor CHECK ((valor >= (0)::numeric))
);

CREATE TABLE public.pdv_crediario_parcela (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    crediario_id uuid NOT NULL,
    venda_id uuid,
    numero_parcela smallint NOT NULL,
    total_parcelas smallint NOT NULL,
    valor numeric(19,4) NOT NULL,
    valor_pago numeric(19,4) DEFAULT 0 NOT NULL,
    vencimento date NOT NULL,
    pago_em timestamp without time zone,
    forma_pagamento character varying(30),
    status character varying(20) DEFAULT 'ABERTA'::character varying NOT NULL,
    observacao character varying(255),
    criado_em timestamp without time zone DEFAULT now() NOT NULL,
    atualizado_em timestamp without time zone DEFAULT now() NOT NULL,
    crediario_conta_id uuid,
    recebido_por character varying(120)
);

CREATE TABLE public.pdv_crediario_recebimento (
    id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    crediario_parcela_id uuid NOT NULL,
    crediario_conta_id uuid NOT NULL,
    valor_recebido numeric(19,4) NOT NULL,
    forma_pagamento character varying(30) NOT NULL,
    data_recebimento timestamp without time zone DEFAULT now() NOT NULL,
    recebido_por character varying(120) NOT NULL,
    observacoes text,
    criado_em timestamp without time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.pdv_item_venda (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    venda_id uuid NOT NULL,
    produto_id character varying(50),
    codigo character varying(50) NOT NULL,
    nome character varying(120) NOT NULL,
    quantidade numeric(19,4) NOT NULL,
    preco_unitario numeric(19,4) NOT NULL,
    custo_unitario numeric(19,4) DEFAULT 0 NOT NULL,
    margem numeric(19,4) DEFAULT 0 NOT NULL,
    total numeric(19,4) NOT NULL,
    por_peso boolean DEFAULT false NOT NULL,
    ncm character varying(10),
    cfop character varying(6),
    cst character varying(4),
    aliquota_icms numeric(19,4),
    desconto_item numeric(19,4) DEFAULT 0 NOT NULL,
    preco_original numeric(19,4),
    categoria character varying(80),
    unidade character varying(6),
    csosn character varying(3),
    cest character varying(7),
    c_class_trib character varying(6),
    acrescimo_item numeric(19,4) DEFAULT 0 NOT NULL,
    preco_alterado_manual boolean DEFAULT false NOT NULL,
    apresentacao_venda_id uuid,
    fator_para_estoque numeric(19,4),
    quantidade_estoque numeric(19,4),
    gtin_comercial character varying(14),
    pis_cofins_classificacao character varying(20),
    valor_icms_st numeric(19,4) DEFAULT 0 NOT NULL,
    aliquota_icms_efetiva numeric(7,4),
    reducao_bc_icms_efetiva numeric(7,4) DEFAULT 0 NOT NULL
);

CREATE TABLE public.pdv_movimento_caixa (
    id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    caixa_id uuid NOT NULL,
    tipo character varying(20) NOT NULL,
    valor numeric(19,4) NOT NULL,
    saldo_apos numeric(19,4) NOT NULL,
    motivo character varying(255),
    operador character varying(80),
    registrado_em timestamp without time zone NOT NULL,
    autorizado_por character varying(120)
);

CREATE TABLE public.pdv_produto (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    codigo character varying(50) NOT NULL,
    nome character varying(120) NOT NULL,
    preco double precision NOT NULL,
    custo double precision DEFAULT 0 NOT NULL,
    margem double precision DEFAULT 0 NOT NULL,
    estoque numeric(19,4) DEFAULT 0 NOT NULL,
    unidade character varying(10) DEFAULT 'un'::character varying NOT NULL,
    por_peso boolean DEFAULT false NOT NULL,
    categoria character varying(60),
    ncm character varying(10),
    cfop character varying(6) DEFAULT '5102'::character varying,
    cst character varying(4) DEFAULT '400'::character varying,
    aliquota_icms double precision DEFAULT 0,
    ativo boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    estoque_minimo numeric(19,4) DEFAULT 0 NOT NULL,
    alerta_estoque_baixo boolean DEFAULT false NOT NULL,
    codigo_plu character varying(10),
    unidade_compra character varying(10) DEFAULT 'UN'::character varying,
    unidade_estoque character varying(10) DEFAULT 'UN'::character varying,
    unidade_venda character varying(10) DEFAULT 'UN'::character varying,
    fator_conversao numeric(19,4) DEFAULT 1 NOT NULL,
    estoque_maximo numeric(19,4),
    estoque_seguranca numeric(19,4) DEFAULT 0,
    lead_time_dias integer DEFAULT 0,
    cobertura_dias integer DEFAULT 0,
    custo_medio numeric(19,4),
    tipo_produto character varying(20) DEFAULT 'SIMPLES'::character varying NOT NULL,
    ponto_pedido numeric(19,4),
    quantidade_compra_padrao numeric(19,4),
    csosn character varying(3),
    cest character varying(7),
    c_class_trib character varying(6) DEFAULT '000001'::character varying NOT NULL,
    validade date,
    lote character varying(40),
    centro_custo_id uuid,
    pendente_revisao boolean DEFAULT false NOT NULL,
    venda_fracionada boolean DEFAULT false NOT NULL,
    categoria_id uuid,
    rendimento_percent numeric(5,2) DEFAULT 100.00 NOT NULL,
    fiscal_profile_id uuid,
    ean_fabricante character varying(14),
    natureza character varying(12) DEFAULT 'MERCADORIA'::character varying NOT NULL,
    servico_item_lista character varying(10),
    servico_codigo_cnae character varying(7),
    servico_codigo_tributacao character varying(20),
    servico_aliquota_iss numeric(6,4),
    servico_iss_retido boolean DEFAULT false NOT NULL,
    servico_discriminacao_padrao text,
    pis_cofins_classificacao character varying(20) DEFAULT 'NORMAL'::character varying NOT NULL,
    pis_cofins_classificacao_manual boolean DEFAULT false NOT NULL,
    icms_st_classificacao character varying(20) DEFAULT 'INDEFINIDO'::character varying NOT NULL,
    icms_st_classificacao_manual boolean DEFAULT false NOT NULL,
    icms_st_classificacao_confirmado_em timestamp without time zone,
    icms_st_classificacao_confirmado_por character varying(120),
    icms_st_aviso_ack_em timestamp without time zone,
    classificacao_fiscal_insumo character varying(32) DEFAULT 'INDEFINIDO'::character varying NOT NULL,
    classificacao_fiscal_insumo_manual boolean DEFAULT false NOT NULL,
    aliquota_icms_efetiva numeric(7,4),
    reducao_bc_icms_efetiva numeric(7,4) DEFAULT 0 NOT NULL,
    vasilhame_tipo_id uuid,
    conteudo_importado_percentual numeric(7,4),
    origem_mercadoria character varying(1),
    reforma_cclass_override boolean DEFAULT false NOT NULL,
    reforma_cclass_override_motivo character varying(500),
    reforma_cclass_override_em timestamp with time zone,
    reforma_cclass_override_por character varying(255),
    requer_reclassificacao_cclasstrib boolean DEFAULT false NOT NULL,
    cclass_orfao_codigo character varying(6),
    cclass_reclass_sugeridos text,
    cclass_trib_revisado_em timestamp with time zone,
    cclass_trib_revisado_por character varying(255),
    cst_ibs_cbs character varying(3),
    cclass_catalogo_versao character varying(20),
    CONSTRAINT chk_pdv_produto_natureza CHECK (((natureza)::text = ANY ((ARRAY['MERCADORIA'::character varying, 'SERVICO'::character varying])::text[]))),
    CONSTRAINT chk_pdv_produto_pis_cofins_classificacao CHECK (((pis_cofins_classificacao)::text = ANY ((ARRAY['NORMAL'::character varying, 'MONOFASICO'::character varying, 'SUBSTITUICAO'::character varying, 'ALIQUOTA_ZERO'::character varying])::text[]))),
    CONSTRAINT chk_pdv_produto_servico_item_lista CHECK ((((natureza)::text <> 'SERVICO'::text) OR ((servico_item_lista IS NOT NULL) AND (length(TRIM(BOTH FROM servico_item_lista)) > 0)))),
    CONSTRAINT chk_pdv_produto_tipo CHECK (((tipo_produto)::text = ANY ((ARRAY['SIMPLES'::character varying, 'MATERIA_PRIMA'::character varying, 'FABRICADO'::character varying])::text[])))
);

CREATE TABLE public.pdv_venda (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    numero_venda character varying(30) NOT NULL,
    numero_venda_cliente character varying(50),
    emitido_em timestamp without time zone DEFAULT now() NOT NULL,
    forma_pagamento character varying(20) NOT NULL,
    total numeric(19,4) NOT NULL,
    desconto numeric(19,4) DEFAULT 0 NOT NULL,
    valor_recebido numeric(19,4),
    lucro numeric(19,4) DEFAULT 0 NOT NULL,
    margem numeric(19,4) DEFAULT 0 NOT NULL,
    cpf_cliente character varying(14),
    nome_cliente character varying(120),
    operador character varying(80),
    chave_nfe character varying(44),
    numero_nfe character varying(10),
    serie_nfe character varying(3),
    qrcode_nfe character varying(500),
    status character varying(20) DEFAULT 'CONCLUIDA'::character varying NOT NULL,
    observacao_cancelamento character varying(255),
    cancelado_em timestamp without time zone,
    dispositivo_id bigint,
    caixa_id uuid,
    status_fiscal character varying(30),
    protocolo_nfe character varying(20),
    c_stat_nfe character varying(10),
    x_motivo_nfe character varying(500),
    correlation_id character varying(64),
    emitir_nfce boolean DEFAULT false,
    cnpj_cliente character varying(18),
    crediario_cliente_id uuid,
    origem_venda character varying(20) DEFAULT 'PDV'::character varying NOT NULL,
    modelo_fiscal character varying(2),
    cliente_id uuid,
    fiscal_email_status character varying(20),
    fiscal_email_enviado_em timestamp without time zone,
    fiscal_email_erro character varying(500),
    abertura_caixa_id uuid,
    fiscal_emitido_em timestamp without time zone,
    fiscal_tentativas integer DEFAULT 0 NOT NULL,
    chave_nfce_origem character varying(44),
    pedido_id uuid,
    loja_id uuid,
    acrescimo numeric(19,4) DEFAULT 0 NOT NULL,
    order_engine_order_id uuid,
    deposito_id uuid,
    dh_recbto_nfe character varying(50),
    data_emissao_nfe timestamp without time zone,
    competencia_fiscal_em timestamp without time zone,
    fiscal_content_version text,
    CONSTRAINT chk_venda_status CHECK (((status)::text = ANY ((ARRAY['CONCLUIDA'::character varying, 'CANCELADA'::character varying])::text[])))
);

CREATE TABLE public.pdv_venda_pagamento (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    venda_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    forma character varying(30) NOT NULL,
    valor numeric(19,4) NOT NULL,
    troco numeric(19,4) DEFAULT 0 NOT NULL,
    referencia character varying(100),
    registrado_em timestamp without time zone DEFAULT now() NOT NULL,
    numero_parcelas integer,
    bandeira character varying(40)
);

CREATE TABLE public.retail_fornecedor (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    nome character varying(120) NOT NULL,
    cnpj character varying(14),
    email character varying(120),
    telefone character varying(20),
    ativo boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    razao_social character varying(200),
    nome_fantasia character varying(120),
    cpf character varying(14),
    celular character varying(20),
    endereco_logradouro character varying(200),
    endereco_numero character varying(20),
    endereco_complemento character varying(80),
    endereco_bairro character varying(80),
    endereco_cidade character varying(80),
    endereco_uf character varying(2),
    endereco_cep character varying(10),
    observacoes text,
    regime_tributario character varying(40),
    regime_tributario_alerta text
);
